/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as MeRouteImport } from './routes/me'
import { Route as PointsRouteImport } from './routes/points'
import { Route as ApiPublicPrizeAssetFileRouteImport } from './routes/api/public/prize-asset.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrizeAssetFileRoute = ApiPublicPrizeAssetFileRouteImport.update({
  id: '/api/public/prize-asset/$file',
  path: '/api/public/prize-asset/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/history': typeof HistoryRoute
  '/manage': typeof ManageRoute
  '/me': typeof MeRoute
  '/points': typeof PointsRoute
  '/api/public/prize-asset/$file': typeof ApiPublicPrizeAssetFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/history': typeof HistoryRoute
  '/manage': typeof ManageRoute
  '/me': typeof MeRoute
  '/points': typeof PointsRoute
  '/api/public/prize-asset/$file': typeof ApiPublicPrizeAssetFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/history': typeof HistoryRoute
  '/manage': typeof ManageRoute
  '/me': typeof MeRoute
  '/points': typeof PointsRoute
  '/api/public/prize-asset/$file': typeof ApiPublicPrizeAssetFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/history'
    | '/manage'
    | '/me'
    | '/points'
    | '/api/public/prize-asset/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/history'
    | '/manage'
    | '/me'
    | '/points'
    | '/api/public/prize-asset/$file'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/history'
    | '/manage'
    | '/me'
    | '/points'
    | '/api/public/prize-asset/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  HistoryRoute: typeof HistoryRoute
  ManageRoute: typeof ManageRoute
  MeRoute: typeof MeRoute
  PointsRoute: typeof PointsRoute
  ApiPublicPrizeAssetFileRoute: typeof ApiPublicPrizeAssetFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/prize-asset/$file': {
      id: '/api/public/prize-asset/$file'
      path: '/api/public/prize-asset/$file'
      fullPath: '/api/public/prize-asset/$file'
      preLoaderRoute: typeof ApiPublicPrizeAssetFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  HistoryRoute: HistoryRoute,
  ManageRoute: ManageRoute,
  MeRoute: MeRoute,
  PointsRoute: PointsRoute,
  ApiPublicPrizeAssetFileRoute: ApiPublicPrizeAssetFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
